### ISSUE TITLE
DevOps - Group Project Requirements for Containerization

### ISSUE THREAD

**Issue by pattonsgirl** [pattonsgirl/CS3900-AppSoftwareDev#10]
Need to define what deliverables are in group project.  Will be noted in Database Design group project updates.

**Comment by sakahle** [comment]
@pattonsgirl I think our deliverables might go hand in hand with DB Design, so maybe the deliverable for both after the first week could be the init.sql for their group project.

Was thinking of having them use docker-compose after the first day to reduce the things they have to think about along the way as they're learning new concepts.

We'd provide docker-compose.yml as a starting point for the DB Design class and then groups work on their init.sql together, below would be close to the deliverable I'm thinking:
https://github.com/sakahle/wsu-assignment-manifests/tree/main/mariadb

What do you think?
