### ISSUE TITLE
DevOps + DB - Group DB Collaboration

### ISSUE THREAD

**Issue by pattonsgirl** [pattonsgirl/CS3900-AppSoftwareDev#16]
How should groups collaborate on database in container?

**Comment by sakahle** [comment]
@pattonsgirl As far as collaborating on the schema creation goes could they leverage version control for this? Once we get to RDS in the later units they can start persisting the actual data out in AWS for their group project.

**Comment by pattonsgirl** [comment]
Added note in group project description with recommendation to have one group member play "master record keeper": https://github.com/pattonsgirl/CS3900-AppSoftwareDev/blob/main/DatabaseDesign/ProjectUpdate-DBDesign.md

RDS later sounds good!
