### ISSUE TITLE
DevOps - Dockerfile RUN & SQL Query TODO

### ISSUE THREAD

**Issue by pattonsgirl** [pattonsgirl/CS3900-AppSoftwareDev#8]
Need to elaborate / determine TODOs in Assignment 1: https://github.com/pattonsgirl/CS3900-AppSoftwareDev/blob/main/DevOps/Assignment1.md

**Comment by sakahle** [comment]
@pattonsgirl Opened up a PR to address these, let me know if there's anything you think we should change. Thanks!
